server:
  port: 8082
spring:
  application:
    name: account-ms
  datasource:
    url: jdbc:postgresql://localhost:5434/accountdb
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: kafka:29092
    consumer:
      group-id: account-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    properties:
      spring.json.type.mapping: >
        com.mybank.msclientepersona.domain.event.ClientEventDto:com.mybank.mscuentamovimiento.infrastrcuture.kafka.ClientEventDto
      spring.json.trusted.packages: "*"
  cache:
    type: redis
  data:
    redis:
      host: redis
      port: 6379
resilience4j:
  circuitbreaker:
    instances:
      clientValidation:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 30s
        automaticTransitionFromOpenToHalfOpenEnabled: true
        recordExceptions:
          - feign.FeignException
          - java.net.ConnectException
          - java.net.SocketTimeoutException
          - java.io.IOException
  retry:
    instances:
      clientValidation:
        maxAttempts: 3
        waitDuration: 500ms
client:
  ms:
    url: http://localhost:8081